### ISSUE TITLE
Probleem met selecties

### ISSUE THREAD

**Issue by hmvp** [openstate/program-tracker#1]
De javascript code die de begin en eindletter van een selectie uitrekent werkt niet altijd correct

**Comment by bteeuwen** [comment]
Wat werkt precies niet?

**Comment by bteeuwen** [comment]
Als ik een selectie maak middenin een alinea en dat label, dan wordt de link daarna niet goed gelegd tussen het geselecteerde stuk tekst en het label. 

Bijvoorbeeld:
- de zin "D66 wil de onzinnige langstudeerboete zo snel mogelijk afschaffen."  bij programma d66 2012.
- met als label 'afstudeerboete'. 

Als ik over het label zweef, wordt "Een toegankelijk stelsel voor studiefinanciering" gearceerd. 
Als ik daarna op het label klik, zie ik de tekst:
"**Een toegankelijk stelsel voor studiefinanciering.** D66 wil dat Hoger Onderwijs voor iedereen die geschikt is, ook toegankelijk is. Tegelijkertijd moet de kwaliteit van het Hoger Onderwijs verbeterd en talent meer gestimuleerd worden. D66 wil de basisbeurs vervangen door een sociaal leenstelsel en de vrijgekomen gelden investeren in verbetering van de kwaliteit van het onderwijs. Om toegankelijkheid te handhaven wil D66 de terugbetalingstermijn van de lening verlengen naar twintig jaar, zodat afgestudeerden maandelijks minder hoeven terug te betalen. Voor oud-studenten die de lening niet kunnen terugbetalen, wordt de lening na deze tijd kwijtgescholden. Van D66 hoeven studenten die een meerjarige master doen, bijvoorbeeld bij bètastudies, deze extra jaren niet te betalen. D66 wil dat ambitieuze studenten voor het wettelijke collegegeld een tweede studie kunnen volgen, ook als zij hun eerste studie afgerond hebben.*\* **D66 wil de onzinnige langstudeerboete zo snel mogelijk afschaffen. D66 zal zorgdragen voor reparatiemaatregelen als het sociaal leenstelsel negatieve effecten heeft op de toegankelijkheid van het Hoger Onderwijs voor studenten met een achterstandsachtergrond. Studenten die jonger zijn dan 17 jaar en willen deelnemen aan hoger onderwijs, zoals hoogbegaafden, komen bij D66 ook in aanmerking voor financiële ondersteuning.** **"

Volgens Hiram gaat het mis met javascript - tellen van karakters bij markdown text. (bovenstaande wordt door github ook dik gedrukt, maar dat is nog niet te zien bij dat scherm waarbij de tekst bij het label getoond wordt).

**Comment by hmvp** [comment]
Als het goed is zou het nu moeten werken, nu we gebruik maken van rangy ipv een jquery.wrapselection
