### ISSUE TITLE
ImportError: No module named settings_local 

### ISSUE THREAD

**Issue by bteeuwen** [openstate/program-tracker#4]
bij lokaal installeren foutmelding:
[bteeuwen@Ben-2 ~/dev/program-tracker]$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    from programtracker import settings #settings
  File "/Users/bteeuwen/dev/program-tracker/programtracker/settings.py", line 62, in <module>
    from settings_local import *
ImportError: No module named settings_local

**Comment by breyten** [comment]
Je moet natuurlijk wel de installatie instricties volgen ben ;) (Zie https://github.com/breyten/program-tracker )

**Comment by breyten** [comment]
en met name stap 5 dan.

**Comment by bteeuwen** [comment]
:). example weghalen in filename settings_local.py.

**Comment by breyten** [comment]
yup (maar wel een copy doen, geen rename)
