### ISSUE TITLE
Import basic dataset (for testing purposes)

### ISSUE THREAD

**Issue by bteeuwen** [openstate/program-tracker#5]
I'd like to be able to deploy and start from scratch with a small but representative data sample.
This is also useful for other people who want to experiment.

Data could be:
VVD, PvdA and D66 political parties
their 2012 programs
1 themes
paragraphs labelled by this theme.

How to use: 
Could we make an admin-like url import script that deletes all current data (which is none when you start) and fills it with a baseline set?
url:     ..../admin/bootstrap

**Comment by hmvp** [comment]
I made a bootstrap fixture:

git pull for updates
python manage.py loaddata bootstrap

should do the trick

Op 04-10-12 16:42, bteeuwen schreef:

**Comment by bteeuwen** [comment]
what does it do exactly? 
After running it I don't see any data changes.

Unpacking objects: 100% (6/6), done.
From https://github.com/hmvp/program-tracker
   c0cb746..5d9f027  master     -> origin/master
Updating c0cb746..5d9f027
Fast-forward
 core/bootstrap.json |  401 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 401 insertions(+)
 create mode 100644 core/bootstrap.json
(programtracker)[bteeuwen@Ben-2 ~/dev/program-tracker]$ python manage.py loaddata bootstrap
No fixtures found.

Op 4 okt. 2012, om 17:17 heeft hmvp notifications@github.com het volgende geschreven:

**Comment by hmvp** [comment]
It should add parties, program's and sectiontypes.

try "manage.py loaddata core/bootstrap.json"

Op 04-10-12 18:24, bteeuwen schreef:

**Comment by breyten** [comment]
Ik ben nu bezig, maar bootstrap datasetje klopt niet helemaal :)

**Comment by breyten** [comment]
Met de update werkt het nu wel, ff pullen :)

**Comment by bteeuwen** [comment]
Werkt als een trein, top!
