### ISSUE TITLE
Admin: unknown column 'topic_selection.source_id' in 'field list'"

### ISSUE THREAD

**Issue by bteeuwen** [openstate/program-tracker#6]
When I go to admin and click 'selections', i get:
(due to empty dataset?)

OperationalError at /admin/topic/selection/
(1054, "Unknown column 'topic_selection.source_id' in 'field list'")
Request Method: GET
Request URL:    http://127.0.0.1:8000/admin/topic/selection/
Django Version: 1.3
Exception Type: OperationalError
Exception Value:  
(1054, "Unknown column 'topic_selection.source_id' in 'field list'")
Exception Location: /Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/MySQLdb/connections.py in defaulterrorhandler, line 36
Python Executable:  /Users/bteeuwen/.virtualenvs/programtracker/bin/python
Python Version: 2.7.2
Python Path:  
['/Users/bteeuwen/dev/program-tracker',
 '/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg',
 '/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/pip-1.1-py2.7.egg',
 '/Users/bteeuwen/.virtualenvs/programtracker/lib/python27.zip',
 '/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7',
 '/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/plat-darwin',
 '/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/plat-mac',
 '/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/bteeuwen/.virtualenvs/programtracker/Extras/lib/python',
 '/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/lib-tk',
 '/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/lib-old',
 '/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/lib-dynload',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages']
Server time:    don, 4 Okt 2012 18:07:52 +0200

**Comment by breyten** [comment]
This should be fixed in more recent versions -- do a `git pull`, then `./manage.py syncdb` and `./manage.py migrate` again, before importing.

**Comment by bteeuwen** [comment]
Inderdaad gefixt, thx!
